# Generated by Django 3.1.2 on 2020-10-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='fecha',
            field=models.DateTimeField(default='2020-11-24', verbose_name='fecha creado'),
            preserve_default=False,
        ),
    ]
