# Generated by Django 3.1.2 on 2020-10-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_operacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
